### ISSUE TITLE
example on how to use the library

### ISSUE THREAD

**Issue by dportabella** [scalawag/sdom#2]
I've looked at the documentation, but I don't find any example.
Can you please provide an example of how to read a xml file, select some nodes using an xpath and print the element name, attributes and list of children?

**Comment by justinp** [comment]
@dportabella  Sorry... I wasn't notified that you created an issue and I just now saw this. Do you still need help or have you figured it out?

**Comment by dportabella** [comment]
Hi, I see that there examples in the wiki, now. Thanks!
